### ISSUE TITLE
Prevent a sanctioned wallet from claiming a hypercert fraction

### ISSUE THREAD

**Issue by ccerv1** [Network-Goods/hypercerts#109]
Sanctioned countries/regions for geofencing on the dApp: Cuba, Iran, North Korea, Syria, the Crimea region of Ukraine, the so-called Donetsk People’s Republic and the so-called Luhansk People’s Republic. This could be done through server settings or a vendor like https://www.geocomply.com/solutions/geolocation-compliance/

**Comment by ryscheng** [comment]
FYI, Fleek has a simple toggle for this

![Screen Shot 2023-01-20 at 13 48 35](https://user-images.githubusercontent.com/566890/213811513-d78f4a6e-fed8-4a8f-a54a-d68b575c145f.png)

Took about 2 minutes to set up hosting on there in addition to Vercel/Netlify, which we already have. Tracking here.
https://github.com/Network-Goods/hypercerts/issues/111

Is this sufficient?

**Comment by ryscheng** [comment]
https://hypercerts.on.fleek.co/

**Comment by ccerv1** [comment]
@ryscheng I think there may be two separate issues:
- A user in a sanctioned territory is not able to access access the hypercerts dApp
- A wallet that is on a [sanctions list](https://www.chainalysis.com/free-cryptocurrency-sanctions-screening-tools/) cannot be allow-listed

Perhaps you can provide an update after your discussion with legal today.

**Comment by ryscheng** [comment]
For the second one, I think the plan is:
- Manually create the allowlist (e.g. via scripts)
- Have the script filter the allowlist based on integrating with some sanctions list
- Upload these allowlists to IPFS and generate creation URLs for the project owners

Does that seem reasonable?

**Comment by ccerv1** [comment]
Exactly.

**Comment by jmoggr** [comment]
I submitted a request for free API access to the sanction screening tool linked by ccerv1 above.

I am unaware of a better/more correct way of screening for sanctioned wallets.

**Comment by jmoggr** [comment]
I have been given access to the Chainalysis Sanctions API and have been able to work with it.

I have hit a small snag: the API response time + python is very slow, about 1.67 requests/second (the API allows up to 5000 requests/min). I will work on parallelizing this tomorrow morning.

**Comment by ryscheng** [comment]
We might also have access to a tool called CSI.
If you struggle with the rate limit by tomorrow, reach out and I can put you in touch with the team that manages that for us.

**Comment by ccerv1** [comment]
@jmoggr just note that when the round closes (at 11:59pm UTC today), I will take a final snapshot of the wallet addresses.

**Comment by ccerv1** [comment]
I've taken the snapshot. Will wait for your final check and then we can close this out.

**Comment by ccerv1** [comment]
Moving this to complete. Allowlists are all on IPFS.
