### ISSUE TITLE
Remove `impact_scope` and `impact_timeframe` fields from the artwork when these are undefined/infinite

### ISSUE THREAD

**Issue by ccerv1** [Network-Goods/hypercerts#119]
@holkeb can you elaborate on the following cases:

### Case 1
IF
- `impact_scope` = any
- `impact_timeframe` = 0 (indefinite)

THEN 
- both fields are omitted

<img src="https://user-images.githubusercontent.com/42869436/214614242-61a0d396-8a7c-4a40-a6ef-490f092e5afa.png" width="200px">

### Case 2
IF
- `impact_scope` = climate
- `impact_timeframe` = 0 (indefinite)

THEN 
- just timeframe field is omitted?

<img src="https://user-images.githubusercontent.com/42869436/214614711-95cc84a0-b367-4056-a0f3-552c1c835fea.png" width="200px">

### Case 3
IF
- `impact_scope` = any
- `impact_timeframe` = defined

THEN 
- just `impact_scope` tag is omitted?

<img src="https://user-images.githubusercontent.com/42869436/214615097-801665dd-fd1b-4e84-8aaa-121da6281fbf.png" width="200px">
* ignore the fact that this particular example says "indefinite" in the tag :)

**Comment by ccerv1** [comment]
Here's the decision. A working version of this have been implemented in the Figma (cc @smombartz)

IF
- `impact_scope` = "All"
- `impact_timeframe` = 0 (indefinite)

THEN 
- both fields are omitted

ELSE
- both field are displayed

**Comment by holkeb** [comment]
@ccerv1 I still prefer to leave it out. This seems like it is an important thing that you definitely want to change, e.g. don't leave it at ALL, but define your impact area. As that isn't really the behavior we want to see, I would omit it according to the rule we had before.

With the previous rule and making it an advanced feature generally, we might see just 10% with a change in the impact scope or time. 90% would be just displaying the same thing (however, as described above, if it is displayed we have many more changes in those fields)

**Comment by ryscheng** [comment]
This is already implemented. 
https://hypercerts.vercel.app/hypercerts/create

Unless I hear otherwise, we should feature-freeze and ignore all new feature requests in the pre-launch testing / debuggin period.
