### ISSUE TITLE
Create devops playbook

### ISSUE THREAD

**Issue by ccerv1** [Network-Goods/hypercerts#129]

**Comment by ccerv1** [comment]
Core operations:

- [ ] Deploy
- [ ] Pause
- [ ] Upgrade
- [ ] Performance under load

**Comment by ryscheng** [comment]
Amazing, thank you so much for the support.

I think what I'd be looking for is a numbered list so that when we need to do something, the relevant parties can do it without thinking, especially when its in response to crisis. Thanks!!

**Comment by ryscheng** [comment]
Example from Gitcoin
https://github.com/gitcoinco/grants-round/blob/7d11d09d92c862d407a9cef7f926d21582ba8a26/packages/contracts/docs/DEPLOY_STEPS.md

**Comment by ccerv1** [comment]
Other resources for inspo:

- Overall: https://github.com/gitcoinco/grants-round/blob/7d11d09d92c862d407a9cef7f926d21582ba8a26/packages/contracts/README.md
- Deploying contracts: https://github.com/gitcoinco/grant-hub/blob/52329b57894b81aa63947aab86d494d1f5676fe3/contracts/README.md and https://github.com/gitcoinco/grants-round/blob/8e907ca94d207bc7c79ba15b3f0f374d2d80d101/packages/contracts/docs/DEPLOY_STEPS.md
- Upgrading: https://github.com/gitcoinco/grants-round/blob/7a09027437f1ddb35137da7227a8dd2511c03444/packages/contracts/contracts/dummy/upgradeCheck/README.md
- Testing / load performance: https://hardhat.org/tutorial/testing-contracts

**Comment by ccerv1** [comment]
Linked here: https://github.com/Network-Goods/hypercerts-protocol/tree/devops/docs/devops 

Update 2/5: I was able to compile the hypercerts minter contract easily.

Comment to @jmoggr: 
> Given that the ops are fairly limited for now, it might be easier just to have a single markdown page with each of the tasks (rather than a separate page per task), but that’s just my preference
