### ISSUE TITLE
Shorten paths

### ISSUE THREAD

**Issue by ryscheng** [Network-Goods/hypercerts#160]
my thinking is:
- `/hypercerts/dashboard` => `/dashboard`
- `/hypercerts/create` => `/create`
- `/hypercerts/view` => `/view#cid`

etc.

**Comment by ryscheng** [comment]
@ccerv1 what do you think?

@holkeb was arguing maybe we should still use some subdirectory (rename the `/hypercerts` part of the path)

**Comment by ccerv1** [comment]
I support this.
Instead of `/hypercerts` how about `/app` ?

**Comment by ryscheng** [comment]
sgtm, just updated and published in Plasmic FYI
