### ISSUE TITLE
Negligible (or zero) gas fees for minting a hypercert

### ISSUE THREAD

**Issue by ryscheng** [Network-Goods/hypercerts#19]

**Comment by ryscheng** [comment]
P2 is to think about potentially refunding gas fees

**Comment by ccerv1** [comment]
Possible solutions:
a) Airdrop to wallets [we only pay gas for the batch send]
b) Reimburse users for gas fees after claiming [take snapshot --> airdrop ETH]
c) User signs transaction but we pay the gas? (not sure this is possible)

**Comment by ccerv1** [comment]
fwiw, POAP does Option C (on gnosis chain); see here: https://ethereum.stackexchange.com/questions/133039/who-pays-for-gas-fee-of-poap

**Comment by ryscheng** [comment]
One possible solution
https://docs.openzeppelin.com/defender/guide-metatx

**Comment by bitbeckers** [comment]
@ccerv1 quick gas report based on the performance test suite. This also runs some tests with random values for a couple hundred times, hence the range in values.

```bash
| src/HypercertMinter.sol:HypercertMinter contract |                 |         |        |         |         |
|--------------------------------------------------|-----------------|---------|--------|---------|---------|
| Deployment Cost                                  | Deployment Size |         |        |         |         |
| 3881554                                          | 19555           |         |        |         |         |
| Function Name                                    | min             | avg     | median | max     | # calls |
| createAllowlist                                  | 152767          | 167017  | 169867 | 169867  | 12      |
| initialize                                       | 2807            | 2807    | 2807   | 2807    | 1       |
| mintClaim                                        | 223800          | 223800  | 223800 | 223800  | 2       |
| mintClaimFromAllowlist                           | 121075          | 121075  | 121075 | 121075  | 1       |
| mintClaimWithFractions                           | 299078          | 2682917 | 299078 | 7450595 | 3       |
| name                                             | 630             | 630     | 630    | 630     | 1       |
```

Using a [simple gas calculator](https://www.cryptoneur.xyz/gas-fees-calculator) we find -using the median- at current prices:
Deployment: $124
Create allowlist: $5.47
initialize: $0.09
mintClaim: $7.20
mintClaimFromAllowlist: $3.90
mintClaimWithFractions: $9.63

You can see that the transaction with the most variable input is `mintClaimWithFractions` and this is a function of the dynamic amount of fractions used during testing. Another case for allowlisting. We can review again when we have batch allowlist claims implemented.

**Comment by ccerv1** [comment]
@bitbeckers this is great -- and feels very encouraging. I'm comparing with the [previous gas report](https://drive.google.com/file/d/1C99gC6dJIDhsRvApPAOUY3dmDbgTBVmx/view) (I know it's not an apples to apples comparison) but it definitely fees like we're moving in the right direction here.  

Apart from the `mintClaimWithFractions` function, are there any other concerns on your mind

NOTE: This conversation feels relevant to issue #23. @holkeb and I are working on a formula for generating the allowlist and, more importantly, how many fractions are issued per wallet address. There's one version where we let _anyone_ who contributes to a project claim at least one fraction and another version where there is a higher floor to receive a hypercert. Presumably, having shorter allowlists / fewer fractions is better from a gas perspective.

**Comment by bitbeckers** [comment]
I wouldn't worry to much about allow list size since the heaviest calculations are off-chain. The minting of a fraction/token/cert is the most expensive part. To double-check, this is the same test suite but I upped the size of the allowlist from 12 to 100000.

```bash
| src/HypercertMinter.sol:HypercertMinter contract |                 |         |         |          |         |
|--------------------------------------------------|-----------------|---------|---------|----------|---------|
| Deployment Cost                                  | Deployment Size |         |         |          |         |
| 3881554                                          | 19555           |         |         |          |         |
| Function Name                                    | min             | avg     | median  | max      | # calls |
| createAllowlist                                  | 152767          | 167017  | 169867  | 169867   | 12      |
| initialize                                       | 2807            | 2807    | 2807    | 2807     | 1       |
| mintClaim                                        | 99012           | 161406  | 161406  | 223800   | 2       |
| mintClaimFromAllowlist                           | 125170          | 125170  | 125170  | 125170   | 1       |
| mintClaimWithFractions                           | 299078          | 6696782 | 7450595 | 12340675 | 3       |
| name                                             | 630             | 630     | 630     | 630      | 1       |
```

The gas cost went from ~121K to ~125K. Not insignificant, but still far below the cost of minting a claim. I think you could argue -based on what we see here- that as soon as you're minting for others to collect, or more than 2 fractions, the allowlist is the cheapest route. However, that might change since we're now enabling batch minting which comes with it's own benefits.

**Comment by ccerv1** [comment]
@bitbeckers we discussed this today and agreed that users will be expected to pay gas fees on both sides of the transaction -- a project creating a hypercert and a user claiming their fraction of the hypercert. 

One caveat though: we are assuming that the batch claim function ("a user can claim all hypercerts fractions they are allowlisted for in one transaction") also remains gas-efficient. If you feel OK on that topic, then we can close out this issue.

**Comment by bitbeckers** [comment]
@ccerv1 update on the gas costs

```bash
| src/HypercertMinter.sol:HypercertMinter contract |                 |         |         |         |         |
|--------------------------------------------------|-----------------|---------|---------|---------|---------|
| Deployment Cost                                  | Deployment Size |         |         |         |         |
| 4278879                                          | 21539           |         |         |         |         |
| Function Name                                    | min             | avg     | median  | max     | # calls |
| batchMintClaimsFromAllowlists - 30               | 3677489         | 3677489 | 3677489 | 3677489 | 1       |
| batchMintClaimsFromAllowlists - 15               | 1837174         | 1837174 | 1837174 | 1837174 | 1       |
| batchMintClaimsFromAllowlists - 5                | 613916          | 613916  | 613916  | 613916  | 1       |
| createAllowlist                                  | 149026          | 149822  | 149026  | 172926  | 240     |
| initialize                                       | 2763            | 2763    | 2763    | 2763    | 1       |
| mintClaim                                        | 227424          | 227424  | 227424  | 227424  | 2       |
| mintClaimWithFractions                           | 303386          | 2707282 | 303386  | 7515075 | 3       |
| name                                             | 630             | 630     | 630     | 630     | 1       |
```

Deployment: $118
Create allowlist: $4
initialize: $0.08
mintClaim: $6.20
mintClaimWithFractions: $8.35
batchMintClaimsFromAllowlists - 30: $101
batchMintClaimsFromAllowlists - 15: $50
batchMintClaimsFromAllowlists - 5: $17

**Comment by ccerv1** [comment]
Thanks -- I'd like to run some scenarios on actual user behavior, but I expect there will be a lot of users in the ~10-30 allowlist category which will make this transaction's gas fees problematic ... per your point on telegram, this is not aligned with our goals. Let's regroup on it.

**Comment by ccerv1** [comment]
Resolved; deploying on Optimism
