### ISSUE TITLE
Logo and banner images not showing up in generated image

### ISSUE THREAD

**Issue by ryscheng** [Network-Goods/hypercerts#191]
Compare these 2 links:

https://hypercerts.vercel.app/app/create?name=Cool%20Hypercert%202&description=This%20is%20a%20pretty%20cool%20hypercert.%20Just%20look%20at%20him.&externalLink=https%3A%2F%2Fhypercerts.vercel.app%2F&logoUrl=https%3A%2F%2Fw0.peakpx.com%2Fwallpaper%2F680%2F678%2FHD-wallpaper-gamer-logo-cool-desing-game-gamer-gamer-logo-gamers-games-lion-logos.jpg&bannerUrl=https%3A%2F%2Ftherooster.com%2Ffiles%2Fstyles%2Fhero%2Fpublic%2Fcool.jpg%3Fitok%3DS6xMQtTZ&impactScopes%5B0%5D=all&impactTimeStart=2023-02-01&impactTimeEnd=2023-02-07&workScopes=cool%0Ahypercert&workTimeStart=2023-02-02&workTimeEnd=2023-02-05&rights%5B0%5D=Public%20Display&contributors=0x123%0A0xabc%0A0x456&allowlistUrl=https%3A%2F%2Fcloudflare-ipfs.com%2Fipfs%2FQmbK8W4AvkuSTbsHyU9RV6egjJBeurLV74nndTHHj98TnV&fractions=10000

https://hypercerts.vercel.app/app/view?claimId=0x94a04ce2e537eaf2bdabd629de503797e7021e87-10548753374549092367364612830384814555136

**Comment by ryscheng** [comment]
```
Access to image at 'https://w0.peakpx.com/wallpaper/680/678/HD-wallpaper-gamer-logo-cool-desing-game-gamer-gamer-logo-gamers-games-lion-logos.jpg' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by ryscheng** [comment]
So diving in a bit deeper into the html2canvas library, we have CORS turned on, but we cannot assume that any image server will allow CORS requests.

As a temporary measure, I'm prefixing all image URLs with `https://api.allorigins.win/raw?url=` to proxy images through this free CORS proxy. It's very very slow, and leads to noticeable delays in the app. I also assume it won't be particularly stable.

Couple options:
1. We deploy the [html2canvas proxy](https://github.com/niklasvh/html2canvas-proxy-nodejs) somewhere. It's express middleware, and integrates with the html2canvas library via the `proxy` option.
2. We find a paid CORS proxy that we can pay for somewhere. Part of the issue is that many require specific HTTP headers to be set (e.g. auth keys), and we don't have control over the HTTP headers from the html2canvas library unless we fork the library
3. We deploy a free Cloudflare worker. Might need to modify their [default CORS proxy](https://developers.cloudflare.com/workers/examples/cors-header-proxy) to match the interface we currently using with allorigins. 

I'm leaning towards 3 at the moment, but need more time to come back to this

**Comment by ccerv1** [comment]
Yes, I like 3 as well.
I noticed latency issues doing demos / testing this morning.

**Comment by ryscheng** [comment]
Testing a deployment of the CORS proxy at 
https://cors-proxy.hypercerts.workers.dev/?url=

**Comment by ryscheng** [comment]
Code here
https://github.com/Network-Goods/hypercerts/pull/223

Still need to:
- [ ] Add tests
- [ ] Add linting

**Comment by ryscheng** [comment]
Gonna close out this issue, since it should be fixed in what's deployed. Will wrap up the PR separately
