### ISSUE TITLE
Indefinite end date freezes the page in create form

### ISSUE THREAD

**Issue by ryscheng** [Network-Goods/hypercerts#205]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Frontend Dapp

### To Reproduce

1. Goto the create page
2. Click on indefinite end date

### Describe the Bug

Page will freeze

### Expected Behavior

Page is responsive

**Comment by ccerv1** [comment]
Also filed here: https://github.com/Network-Goods/hypercerts/issues/206

**Comment by ryscheng** [comment]
Seems to be related to this change here
https://github.com/Network-Goods/hypercerts/pull/201/files#diff-20a90a607ac961d5c8b5e100d06a5783ae44ab5aebfe5f75ff7e7d9cc36a5fa9R225

I've reverted some changes in this PR
https://github.com/Network-Goods/hypercerts/pull/213

Don't love the current fix, will look a little deeper, or give up if this takes too long

**Comment by ryscheng** [comment]
Dang. This seems unrelated to https://github.com/Network-Goods/hypercerts/issues/211

That issues seems more important right now so I'm going to close this for now while I dig into that.

**Comment by ryscheng** [comment]
To clarify, the latest deployment shouldn't have this issue
https://hypercerts.vercel.app/app/create?
