### ISSUE TITLE
A Project can create a hypercert

### ISSUE THREAD

**Issue by ryscheng** [Network-Goods/hypercerts#21]
that represents an approved scope of work and scope of impact claim on an EVM chain

**Comment by holkeb** [comment]
Comments and questions regarding the create page. @ccerv1 can you check these and see if you agree? After we agree we can pass it on to @ryscheng to see if it also makes sense technically

1. The transition between the image and the background would be gradual ideally (see picture)
![Image](https://user-images.githubusercontent.com/103380539/216150533-b4d27edf-079a-4d28-ad5a-805b859f98c1.png)

2. For this pilot we would also fix the time of work or at least the work end date, such that the hypercert is always referring to past work. @ccerv1 we also have a reasonable work start date, right? Alternative we could prevent any work end date that's in the future.

3. The `impact start date` should be fixed being the same as the `work start date`. The `impact end date` should be `indefinite`.

4. I would put the section on `impact scope` and the `usage rights` at the end as an `Advanced` section. This can be toggled. When it opens it says: "The advanced options are fixed for this round" (or something like that). It makes the form appear shorter and tells the user that they don't really have to worry about it, but they can find out what it is if they want to.

5. I can only update the logo or background if I upload it somewhere else. Would be a nice-to-have to be able to just upload it in the form directly to be used.

6. Can we include tooltips somewhere or is that planned already? i.e. if I hover or click on a field name

**Comment by holkeb** [comment]
7. "Project name" should probably be "Name of hypercert" or "Hypercert title" (whatever sounds better to you as native speakers)

**Comment by ccerv1** [comment]
Thanks Holke! Some good stuff here. At the end of the week, I will consolidate these requests. Most are either in the plan already (eg, tooltips) or relatively easy to implement (eg, ordering of fields in the form).

**Comment by holkeb** [comment]
8. It would be great if boxes like the description could be expanded to see more content

**Comment by ccerv1** [comment]
also need to review character limits for the description

**Comment by ryscheng** [comment]
Thanks for the feedback!
I don't want to lose your feedback, but please file *new* issues for every individual piece of feedback.
Otherwise these issues never get marked completed
CC @holkeb 

Going to close this for now, since we have completed the original scope of the task, creating a hypercert
