### ISSUE TITLE
Infinite loop in the create form

### ISSUE THREAD

**Issue by ryscheng** [Network-Goods/hypercerts#211]
### To Reproduce

Create any hypercert. Try to mint

### Describe the Bug

Chrome crashes

### Expected Behavior

it doesn't

**Comment by ryscheng** [comment]
![Screen Shot 2023-02-08 at 09 06 49](https://user-images.githubusercontent.com/566890/217605254-751259c7-affb-449c-9551-56044ce34970.png)

**Comment by ryscheng** [comment]
https://github.com/Network-Goods/hypercerts/pull/215

**Comment by ryscheng** [comment]
Fixed. The useEffect dependency loop turned into an infinite loop with Metamask. Whoops.

**Comment by ccerv1** [comment]
Woot woot woot!

**Comment by ryscheng** [comment]
https://github.com/Network-Goods/hypercerts/pull/224

Removing this lint rule for good
