### ISSUE TITLE
feat(mint_url): the `fractions` passed in the mint url should reflect the fraction total in the allowlist

### ISSUE THREAD

**Issue by ccerv1** [Network-Goods/hypercerts#219]
### Describe the feature you'd like to request

Metadata and URL should capture the total fractions available on the allowlist

### Describe the solution you'd like

When the allowlist is generated, the sum of fractions should be calculated and passed as hidden property in the metadata and to the `fractions` field in the minting URL

### Describe alternatives you've considered

The alternative was to hardcode every project to 100,000 fractions

**Comment by ryscheng** [comment]
https://github.com/Network-Goods/hypercerts/pull/225

- removed fractions from the URL
- mintClaim is adjusted to always mint 10000 units
- mintClaimAllowlist unchanged --- sums up the units from the allowlist to be the totalSupply
