### ISSUE TITLE
(bug) contributor list must be a string but the value passed through the url is an array

### ISSUE THREAD

**Issue by ccerv1** [Network-Goods/hypercerts#221]

**Comment by ccerv1** [comment]
I can investigate this. I think it's an issue with the metadata being converted to a minting url. Will revert back if not.

![Image](https://user-images.githubusercontent.com/42869436/217908950-591052cb-9081-4b72-afce-e8d32a6e3037.png)

@ryscheng this bug came from an early test user!

**Comment by ryscheng** [comment]
Interesting, can you share the minting URL?

**Comment by ccerv1** [comment]
> Interesting, can you share the minting URL?

[Here](https://hypercerts.vercel.app/app/create?name=OpSci%20Society%3A%20The%20Open%20Science%20DAO&description=OpSci%20builds%20open%20source%20tooling%20for%20web-native%20identity%2C%20reputation%2C%20funding%2C%20and%20reproducible%20science.%20%20%0A%0AThe%20OpSci%20ecosystem%20is%20composed%20of%20three%20services%3A%20%0A%0A1%29%20Commons%20-%20a%20decentralized%20data%20commons%20that%20offers%20free%20archival%20for%20large%20reproducible%20neuroimaging%20datasets.%0A%0A2%29%20Verse%20-%20a%20DeSci%20Society%20registry%20that%20links%20verifiable%20impact%20with%20funding%20streams%20on-chain.%0A%0A3%29%20Fellowship%20-%20a%20permission-less%20grant%20program%20that%20provides%20a%20stipend%20for%20researchers%20at%20all%20levels%20performing%20work%20at%20the%20intersection%20of%20Web3%20and%20DeSci.&externalLink=https%3A%2F%2Fopsci.io&logoUrl=https%3A%2F%2Fcloudflare-ipfs.com%2Fipfs%2Fbafkreic3mwzm5hkjrto7jt3hbstra3owkwi2olc7iv2g7wfgxydombjn6m&bannerUrl=https%3A%2F%2Fcloudflare-ipfs.com%2Fipfs%2Fbafybeiegmfnfzvzhagmyjnn3djubzbhajcd4eeka5sbkhh7dency2dbmay&impactScopes%5B0%5D=all&impactTimeEnd=2023-02-09&workScopes=OpSci%20Society&workTimeStart=2022-09-22&workTimeEnd=2023-01-10&rights%5B0%5D=Public%20Display&contributors%5B0%5D=0x33359285F30E7B3386dE70ca500F4fe27853765B&allowlistUrl=ipfs%3A%2F%2Fbafybeigcogqgin67mtssk5fhprxvvysk74lmki4i6eqk6iuurlvu4vzopm%2FOpSci%20Society-%20The%20Open%20Science%20DAO.csv&backgroundColor=blue&backgroundVectorArt=octagonals&fractions=100000&impactTimeStart=2023-01-10) it is

**Comment by ryscheng** [comment]
Ya I think this is an issue with the URL generation. `workScopes` and `contributors` are both textfields. But notice how they're represented in the URL:
```
workScopes=OpSci%20Society
contributors%5B0%5D=0x33359285F30E7B3386dE70ca500F4fe27853765B
```

The characters after contributors is causing the form to interpret it as an array as opposed to a string. (We want a comma-delimited string).

Also, you can remove `impactTimeStart` and `fractions` from the URL generation scripts too

**Comment by ccerv1** [comment]
Fixed and merged the PR
