### ISSUE TITLE
A Hypercert Creator can set the total supply of hypercerts it wants to issue

### ISSUE THREAD

**Issue by ryscheng** [Network-Goods/hypercerts#23]

**Comment by holkeb** [comment]
We should consider the option that all hypercerts have the same supply, e.g. 10^10. The number of tokens/units isn't relevant, but the percentage of the total impact.

Pro:
- one variable less for projects to decide
- having a certain number of tokens/units always translates to the same percentage for all hypercerts
- ...

Cons:
- it doesn't feel scarce if there are 10^10 tokens (if the percentage is prominent that would create the scarcity)
- ...

**Comment by ccerv1** [comment]
No objection to this, though I heard the number 10^3 floating around as well. 

If 10^3, then each unit of 1 represents a basis point share of the hypercert, which may be more intuitive.

**Comment by ccerv1** [comment]
@holkeb @ryscheng moving this to an open question. 
I'm currently operating on the assumption that there will be a fixed supply, eg, 10^3. We should nail this down.

**Comment by ryscheng** [comment]
I don't mind any value we choose.
But just to check the math:
- 10^1 means 10 tokens, so 1 token equals 10%
- 10^2 means 100 tokens so 1 token equals 1%
- 10^3 means 1000 tokens, so 1 token equals 0.1%
- 10^4 means 10000 tokens, so 1 token equals 0.01% or 1 basis point

Did I get that right?

**Comment by holkeb** [comment]
Is there a reason why we shouldn't just choose something large like 10^10? I don't see that we have such small pieces right now, but maybe at some point some individual puts in $5 and some foundation $1M. The number of tokens should be in the background from my perspective and the share should be in the focus.

**Comment by ryscheng** [comment]
I can see the value of that, a high total supply translates to more decimals of precision when calculating the percentage ownership.

**Comment by ccerv1** [comment]
@ryscheng 
> 10^3 means 1000 tokens, so 1 token equals 0.1%

Whoops! My bad ... I had meant 10^4 !

@holkeb 
> Is there a reason why we shouldn't just choose something large like 10^10?

I'm ambivalent!

Here are some reasons for a smaller number, eg 10^4 

- signals scarcity
- has the effect of creating a floor for more popular projects (eg, you need to contribute at least $10 for a project that raises $100K to claim a hypercert)
- feels more like other ERC1155 use cases -- most [top projects](https://dune.com/queries/461434) on opensea appear to have total supply between 10^3 and 10^5
- big numbers could introduce UX issues on 3rd party sites like opensea. Here is a [sample ERC1155 project](https://opensea.io/assets/ethereum/0x6d4bbc0387dd4759eee30f6a482ac6dc2df3facf/1) that I overwrote with a larger available supply


![Image](https://user-images.githubusercontent.com/42869436/210696512-f65e6449-ce00-4764-be3f-81984b614224.png)

**Comment by miyazono** [comment]
Another reason not to choose 10*10: you can't store it in an int.  Keep it
under 4 bytes please [image: 🙏]

*Evan Miyazono, Ph.D.*
Head of Network Goods *|* Protocol Labs
calendly.com/miyazono/30-min

**Comment by bitbeckers** [comment]
Would this be for our implementation, or the interface specification? 

This decision touches on a lot of aspects, from minting methods to the front-end. A quick-solution could be to hardcode the value in the FE, maybe even in our implementation, but leaving it open for the protocol to remain fairly unopiniated.

If it applies to all hypercerts, we should set this on a contract level and declare it in docs. It would also inform the decision on how we handle the bit split.

But I think my point is clear, let me know what you want :)

**Comment by ccerv1** [comment]
@holkeb and I discussed yesterday and he's going to make a recommendation.

I agree that the protocol should be un-opinionated. Personally, I'm fine with just hardcoding the value in the FE and leaving it open in our implementation.

**Comment by holkeb** [comment]
- If my research is correct, Evan says max 10^9. I think we don't need to go bigger (10^10 was just an arbitrary high number)
- If we would assume that everyone who at least contributes $1 should get a hypercert, then the total value of a hypercert would be equal to the tokens we would need (not accounting for decimals). E.g. if the total value of a hypercert is 10,000, we would need 10,000 tokens. So, I could see a world, where we want more than 10,000 tokens as a large hypercert might be larger than $10,000. And if they do crowdfunding, some might only contribute very small amounts (not saying that they raise all the money via crowdfunding)
- I'm ok with leaving the protocol un-opinionated. @bitbeckers: Or would it makes things much simpler if we would choose for instance 10^9? (even though it wouldn't be your preference)

@ccerv1 I would set the number in the pilot such that we are quite sure that everyone who contributes at least $1 would be eligible for a hypercert

**Comment by ryscheng** [comment]
I think it'll be easier to leave the protocol unopinionated and set it in the front-end. At the end of the day, either way, we need to calculate `value / total` for the percentage.

**Comment by holkeb** [comment]
Decisions: 
- Protocol will be unopinionated
- For now we assume that we will use 10.000 tokens for all the hypercerts in the pilot. We'll set that in the frontend. Users can't change it. When we have the data from the round, we can revise the decision, potentially adding one or two or more zeros.
