### ISSUE TITLE
fix(create): a description should be limited to 1500 chars

### ISSUE THREAD

**Issue by ccerv1** [Network-Goods/hypercerts#231]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Frontend Dapp

### To Reproduce

[Here](https://hypercerts.vercel.app/app/create?name=OpSci%20Society%3A%20The%20Open%20Science%20DAO&externalLink=https%3A%2F%2Fopsci.io&logoUrl=https%3A%2F%2Fgitcoin.mypinata.cloud%2Fipfs%2Fbafkreic3mwzm5hkjrto7jt3hbstra3owkwi2olc7iv2g7wfgxydombjn6m&bannerUrl=https%3A%2F%2Fgitcoin.mypinata.cloud%2Fipfs%2Fbafybeiegmfnfzvzhagmyjnn3djubzbhajcd4eeka5sbkhh7dency2dbmay&backgroundColor=blue&backgroundVectorArt=octagonals&workTimeStart=2022-09-22&workTimeEnd=2023-01-10&impactTimeEnd=indefinite&rights%5B0%5D=Public%20Display&workScopes=OpSci%20Society&impactScopes%5B0%5D=all&contributors=0x33359285F30E7B3386dE70ca500F4fe27853765B&allowlistUrl=https%3A%2F%2Fipfs.io%2Fipfs%2Fbafybeigcogqgin67mtssk5fhprxvvysk74lmki4i6eqk6iuurlvu4vzopm%2FOpSci%2520Society-%2520The%2520Open%2520Science%2520DAO.csv&description=OpSci%20builds%20open%20source%20tooling%20for%20web-native%20identity%2C%20reputation%2C%20funding%2C%20and%20reproducible%20science.%20%20%0A%0AThe%20OpSci%20ecosystem%20is%20composed%20of%20three%20services%3A%20%0A%0A1%29%20Commons%20-%20a%20decentralized%20data%20commons%20that%20offers%20free%20archival%20for%20large%20reproducible%20neuroimaging%20datasets.%0A%0A2%29%20Verse%20-%20a%20DeSci%20Society%20registry%20that%20links%20verifiable%20impact%20with%20funding%20streams%20on-chain.%0A%0A3%29%20Fellowship%20-%20a%20permission-less%20grant%20program%20that%20provides%20a%20stipend%20for%20researchers%20at%20all%20levels%20performing%20work%20at%20the%20intersection%20of%20Web3%20and%20DeSci.&) is an example of a description that is between 500 and 1500 chars

### Describe the Bug

The app refuses to mint and throws an on-screen warning that the description is too long (>500 chars)

### Expected Behavior

The app should support a description up to 1500 chars in length

**Comment by ryscheng** [comment]
https://github.com/Network-Goods/hypercerts/pull/234

**Comment by ccerv1** [comment]
I am still getting a 1500 char warning with [this attempt](https://hypercerts.vercel.app/app/create?name=Web3beach&description=Accelerating%20web3%20education%20and%20adoption%20through%20social%20and%20environmental%20impact.%20%22Impact%20Onboarding%22%20creates%20onramps%20and%20upward%20mobility%20in%20web3%20for%20unbanked%2C%20disenfranchised%2C%20and%20historically%20overlooked%20communities.%20WEB3BEACH%20educates%2C%20coaches%20and%20empowers%20community%20leaders%20from%20diverse%20walks%20of%20life%20to%20use%20web3%20tools%20in%20efforts%20to%20improve%20living%20conditions%20for%20all.%20This%20includes%20environmental%20impact%2C%20health%20services%2C%20education%2C%20recreation%20and%20the%20ability%20to%20carry%20out%20their%20own%20public%20goods%20initiatives%20through%20our%20mini%20grants%20program.%20As%20a%20byproducts%2C%20we%27re%20creating%20circular%20crypto%20economies%20in%20our%20communities.%20%0A%0ASince%20GR15%3A%20We%27ve%20launched%20programs%20in%20five%20communities%20throughout%20Honduras%20and%20will%20continue%20to%20expand%20in%202023.%20We%27re%20also%20advising%20projects%20in%20other%20countries%20so%20they%20can%20adopt%20Impact%20Onboarding%20strategies%20in%20their%20region.%20%0A%0A%0A%F0%9F%94%8DTransparency%20Reports%3A%20We%20include%20expense%20reports%20with%20all%20of%20our%20events%20and%20currently%20working%20towards%20creating%20a%20standardized%20grantee%20reporting%20process.%20%0A%0A%0AOur%20services%20include%3A%0A%0A%F0%9F%8C%8AEnvironmental%20Impact%0A%F0%9F%8F%A5Health%20Services%0A%F0%9F%91%A9%E2%80%8D%F0%9F%8F%ABEducation%0A%F0%9F%92%B8Economic%20support%20for%20micro%20entreprenuers%0A%F0%9F%AB%B0%F0%9F%8F%BEMini%20grants%20program%0A%0A%0ACommunity%20Services%20offered%20since%20GR15%3A%0A%0AEnvironmental%20Impact%20-%20Beach%20clean%20ups%20%0Ahttps%3A%2F%2Ftwitter.com%2Fweb3beach%2Fstatus%2F1597629431597903872%0Ahttps%3A%2F%2Ftwitter.com%2Fweb3beach%2Fstatus%2F1603773200017784833%0A%0A%0AMental%20Health%20services%20-%20Therapy%20for%20Honduran%20buidlers%0Ahttps%3A%2F%2Ftwitter.com%2Fweb3beach%2Fstatus%2F1595500429898665985%0A%0AKids%20web3%20education%3A%0Ahttps%3A%2F%2Ftwitter.com%2Fw&externalLink=https%3A%2F%2Fweb3beach.io%2F&logoUrl=https%3A%2F%2Fgitcoin.mypinata.cloud%2Fipfs%2Fbafkreih4es2d5t6twhario7f2xopopz77f3pqpux46so4xgvjzhaos632y&bannerUrl=https%3A%2F%2Fgitcoin.mypinata.cloud%2Fipfs%2Fbafkreiatmypzrrw6rrnxdxs6wzkubzr7eskm243t3b4kfuz6g3k3bwerqa&impactScopes%5B0%5D=all&impactTimeEnd=indefinite&workScopes=Web3beach&workTimeStart=2022-09-22&workTimeEnd=2023-01-10&rights%5B0%5D=Public%20Display&contributors=0xEFEdaf9c07E6eB56BB8F82f30018e4461B1c5F4c&allowlistUrl=https%3A%2F%2Fipfs.io%2Fipfs%2Fbafybeigcogqgin67mtssk5fhprxvvysk74lmki4i6eqk6iuurlvu4vzopm%252FWeb3beach.csv&backgroundColor=green&backgroundVectorArt=circles)

**Comment by ccerv1** [comment]
I reduced the char limit in the python script to 1400. This can be refactored some other time. Closing out.
