### ISSUE TITLE
bug: hypercert failing to mint

### ISSUE THREAD

**Issue by ccerv1** [Network-Goods/hypercerts#239]
After minting two hypercerts in rapid succession, the third failed to mint. Error message below.

![Image](https://user-images.githubusercontent.com/42869436/218218701-336d2ac1-0932-4ade-adeb-6dd62eae683f.png)

console trace (1/2):

![Image](https://user-images.githubusercontent.com/42869436/218218946-2d203305-c18f-440e-98dd-8505301181d9.png)

console trace (2/2):

![Image](https://user-images.githubusercontent.com/42869436/218219002-70c89cd4-133d-4733-a711-ed5d8acc8b57.png)

form-submit values all look OK.

**Comment by ccerv1** [comment]
OK, still failing. Here is the [url](https://hypercerts.vercel.app/app/create?name=BanklessDAO%20Projects&description=THE%20BANKLESSDAO%20MISSION...%0ABanklessDAO%20is%20a%20decentralised%20community%20coordinating%20and%20propagating%20bankless%20media%2C%20culture%2C%20and%20education.%20BanklessDAO%20launched%20on%20May%204%2C%202021%2C%20and%20its%20goal%20is%20to%20drive%20adoption%20and%20awareness%20of%20truly%20bankless%20money%20systems%20like%20Ethereum%2C%20DeFi%2C%20and%20Bitcoin.%0ATogether%2C%20the%20BanklessDAO%20community%20collaborates%20to%20create%20user-friendly%20onramps%20for%20people%20to%20discover%20decentralised%20financial%20technologies%20through%20education%2C%20media%20and%20culture.%0AThe%20BanklessDAO%20community%20runs%20a%20variety%20of%20projects%3B%20for%20the%20scope%20of%20this%20grant%20we%20are%20focusing%20on%20the%20ones%20which%20truly%20provide%20goods%20and%20services%20for%20the%20entire%20world%20such%20as%20BANKLESS%20ACADEMY%2C%20BANKLESS%20AFRICA%2C%20and%20INTERNATIONAL%20MEDIA%20NODES.%20%0AThe%20projects%20listed%20below%20have%20had%20contributors%20working%20on%20them%20for%20many%20months%20and%20although%20some%20of%20the%20project%20contributors%20earn%20governance%20tokens%2C%20the%20work%20being%20done%20far%20outstrips%20the%20existing%20remuneration.%20Second%2C%20and%20perhaps%20more%20important%2C%20is%20that%20all%20these%20projects%20aim%20to%20help%20the%20wider%20crypto%20ecosystem%20and%20not%20just%20the%20Bankless%20community%20%E2%80%94%20and%20hence%20are%20public%20goods.%0ABANKLESS%20ACADEMY%0A%F0%9F%9A%80%20Brief%0ABankless%20Academy%20is%20a%20leading%20web3%20%22knowledge%20on-ramp%22%20-%20a%20practical%20%26%20engaging%20education%20experience%20with%20infrastructure%20preparing%20to%20be%20scaled%20across%20the%20blockchain%20multiverse.%0AWe%27re%20helping%20the%20world%20adopt%20the%20permissionless%20tools%20they%20need%20to%20go%20Bankless.%0A%F0%9F%94%A5%20Vision%0AWe%20are%20building%20&externalLink=https%3A%2F%2Fwww.bankless.community%2F&logoUrl=https%3A%2F%2Fgitcoin.mypinata.cloud%2Fipfs%2Fbafkreifhgemr6res2dsvkqy26vc4eveaf2g6qmjdqg3rnjal6cy4lmorwq&bannerUrl=https%3A%2F%2Fgitcoin.mypinata.cloud%2Fipfs%2Fbafybeigxjivwgcz4njxfdky5yw7kzysfghusf6j72srucr3adn4msgryde&impactScopes%5B0%5D=all&impactTimeEnd=indefinite&workScopes=BanklessDAO%20Projects&workTimeStart=2022-09-22&workTimeEnd=2023-01-09&rights%5B0%5D=Public%20Display&contributors=0xf26d1Bb347a59F6C283C53156519cC1B1ABacA51&allowlistUrl=https%3A%2F%2Fipfs.io%2Fipfs%2Fbafybeigcogqgin67mtssk5fhprxvvysk74lmki4i6eqk6iuurlvu4vzopm%252FBanklessDAO%2520Projects.csv&backgroundColor=blue&backgroundVectorArt=octagonals)

**Comment by ccerv1** [comment]
note: this project has a long allowlist -- over 3000.

**Comment by ccerv1** [comment]
I was able to mint another hypercert (smaller allowlist) just now

**Comment by ccerv1** [comment]
I got a `429 Too Many Requests` error from the allowlist gateway on ipfs.io

**Comment by ryscheng** [comment]
Can we try a different IPFS gateway if that one rate-limits too aggressively?

**Comment by ccerv1** [comment]
I think the rate limiting is the issue. I'm going to close this out but log two issues:
- A user should receive an error if an IPFS gateway is rate-limiting access to an IPFS asset
- Set-up our own IPFS gateway on cloudflare or pinata
