### ISSUE TITLE
A Hypercert Creator can upload a whitelist of wallets that are eligible to claim shares of hypercerts

### ISSUE THREAD

**Issue by ryscheng** [Network-Goods/hypercerts#24]

**Comment by ccerv1** [comment]
Zora's implementation seems very similar to what we need: https://support.zora.co/en/articles/6536768-how-to-create-an-allowlist

**Comment by ryscheng** [comment]
This is sufficiently done to work.
If we want to do more to mimic Zora's UX, let's file a new issue
