### ISSUE TITLE
[Ops] Select Gitcoin round participants

### ISSUE THREAD

**Issue by ryscheng** [Network-Goods/hypercerts#29]
10 ish?

**Comment by ccerv1** [comment]
Update: Carl will connect with Gitcoin team (Kieren + Ben) to agree on eligibility requirements for the round. Need to address concerns around quid-pro-quo if only some projects are eligible to mint hypercerts and how this is surfaced to users (funders).

**Comment by ccerv1** [comment]
Update: Carl is in touch with Kieren and Ben and has shared the projects' [database](https://docs.google.com/spreadsheets/d/1RrIDRXgyDQgoPu0GvpTywQswqu6vmccrbxjtlx7yEwo/edit?usp=sharing) and current review methodology.

**Comment by ccerv1** [comment]
Closing this out: I got resolution from the Gitcoin team on how eligibility will be finalized. 

See this [doc](https://docs.google.com/document/d/1i-TKc66V0AEi_TVu2eAwYLxV_W76Oclai3p3PKqNiHo/edit?usp=sharing) and this info on the application page for each round ([this one is for OSS](https://grant-explorer.gitcoin.co/#/round/1/0xd95a1969c41112cee9a2c931e849bcef36a16f4c))

Plus:
> We'll review applications on a rolling basis, but I believe only the round managers can see the list of who applied and was accepted. So I think yes - the public list of grants in the round won't be available until the round starts on Jan 17th
