### ISSUE TITLE
An allowlist of wallets that are eligible to claim a hypercert fraction can be generated by taking a snapshot of wallet addresses that donated to its Gitcoin Grant

### ISSUE THREAD

**Issue by ryscheng** [Network-Goods/hypercerts#32]

**Comment by ccerv1** [comment]
Something similar to: https://support.zora.co/en/articles/6536768-how-to-create-an-allowlist

**Comment by ccerv1** [comment]
See here for contract data:
- Climate: https://dune.com/umarkhaneth/gitcoin-alpha-climate-solutions
- ETH Infra: https://dune.com/umarkhaneth/gitcoin-alpha-eth-infra
- OSS: https://dune.com/umarkhaneth/gitcoin-alpha-open-source-software

**Comment by ccerv1** [comment]
Completed [here](https://github.com/Network-Goods/hypercerts/blob/main/utils/allowlist.py). Closing this out.
