### ISSUE TITLE
[Outreach] Plan marketing campaign with Gitcoin and Supermodular

### ISSUE THREAD

**Issue by ryscheng** [Network-Goods/hypercerts#38]
https://docs.google.com/document/d/1BMXeU3Y_8Xx2IL_ch5Bmr5-lQ5Z8giD6JJbexJcaLA4/edit?usp=sharing

**Comment by ccerv1** [comment]
Need to understand Gitcoin's plans for POAP drops for participants in the alpha round

**Comment by holkeb** [comment]
@ccerv1 put my thoughts in here: https://docs.google.com/document/d/1BMXeU3Y_8Xx2IL_ch5Bmr5-lQ5Z8giD6JJbexJcaLA4/edit?usp=sharing (included in the top) please have a look if that makes sense to you and please add and edit

I included the public communication and also some of the project only communication as it seems good to have that in one place as an overview

**Comment by ccerv1** [comment]
This is great @holkeb 
Do you want to loop in Liam? I think he can help!

**Comment by holkeb** [comment]
ah, yes, absolutely: @liam-ohagan looping you in here :)

The above document describes a bit our marketing plans for the pilot. Happy jump on a call to explain more (feel free to just put something on my and Carl's calendar that works for you)

**Comment by liam-ohagan** [comment]
hey hey

From what I can see, it's mostly twitter posts and emails that you need help with? But will pop in a calendar invite to discuss it further

**Comment by ccerv1** [comment]
I'm going to close this out and we can create new issues for specific outreach campaigns
