### ISSUE TITLE
Batch hypercert minting from multiple projects in one transaction

### ISSUE THREAD

**Issue by ryscheng** [Network-Goods/hypercerts#43]
P2: A user can claim all hypercerts they are eligible for in one transaction (they don’t need to sign / pay gas on 10 transactions)

**Comment by ryscheng** [comment]
@ccerv1 has a good point that we can use the Gitcoin graph instance to query which projects a user has funded, then use that as a hint to know which allowlists fetch from IPFS.

**Comment by bitbeckers** [comment]
We discussed the following flow:
- Query Grants Graph for participated rounds of signed in user
- Call IPFS for all metadata -> allowlists
- Parse and gather all proofs
- Submit batchMintingFromAllowlist transaction

**Comment by bitbeckers** [comment]
Contract developments in: https://github.com/Network-Goods/hypercerts-protocol/pull/88

**Comment by Jipperism** [comment]
@ryscheng cc: @bitbeckers

After spending some time on this we still didn't really come up with a watertight solution.

As of now, I only see 3 options:

***brute force***
1. download all metadata for all claims where an allowlist is present
2. download all allowlists for those claims and parse
3. check what allowlists current user is present in

***using grants graph***
get all `qfvote` for currently logged in user, and projectId for current vote.
the problem then becomes to create a relationship `grantsRoundQfVote.projectId -> claim`. We could allow for specifying a grants round projectId when minting a claim with allowlist. Another option is to emit the projectId together with the allowlist entity on the graph. Both these options mean that we are optimizing our graph and integrating gitcoin data for this usecase, essentially using it as a datastore.

***use datastore***
use some sort of data store. upon minting using the allowlist function, create pairs with address<>certId. When visiting the batch mint page, request all pairs for current user and use that.

**Comment by ryscheng** [comment]
During the standup discussed using option 3 - use datastore, backed by Google sheets for now

**Comment by Jipperism** [comment]
@bitbeckers to add those `[address, claimId]` pairs to the data store, I'd need to somehow get the claim-id for the generated hypercert upon mint. Would there be a way to return that?

**Comment by Jipperism** [comment]
@bitbeckers also, not entirely sure if the graph is updated correctly after batch minting. The fractions don't seem to show up for me on the graph at least. See https://goerli.etherscan.io/tx/0x388e45940c5da5fcdfeb92ed013b22a71f86907fa42e6daa30d93dc6173695a0 and the absence of the correct fractions on the graph.

**Comment by bitbeckers** [comment]
> https://github.com/Network-Goods/hypercerts/issues/43#issuecomment-1398134807

Correct, there is a new event that needs to be parsed: `event BatchValueTransfer(uint256[] claimIDs, uint256[] fromTokenIDs, uint256[] toTokenIDs, uint256[] values);`

Working on that today

**Comment by Jipperism** [comment]
> @bitbeckers to add those [address, claimId] pairs to the data store, I'd need to somehow get the claim-id for the generated hypercert upon mint. Would there be a way to return that?

@ryscheng bitbeckers and I discussed the following things:
* we will monitor for the `emit ClaimStored(claimID, _uri, units);` event.
* when the event is observed parse the claim data again, and update the data store

The drawback of this approach is that users should not close the window before the data store is updated. We figured we will add a banner to warn them not to do that, and since it's stored in sheets.best it's relatively straight forward to update that at a later point if necessary.

A more solid approach would be to run a service that waits for these events, but it will add complexity. Please let me know if that is the preferred way forward.

**Comment by ryscheng** [comment]
seems reasonable for now. Thanks!

**Comment by Jipperism** [comment]
@ryscheng @ccerv1 it shouldn't be hard to make it so, that when minting a claim with a predefined allowlist uri (as is the plan currently, to reduce friction when onboarding during the upcoming git round), to update supabase upon minting the claim. this way, you would just have to upload the merkle tree json to ipfs and pre-populate the allowlist cid field. i would then download it and add those entries to supabase upon mint.

**Comment by ryscheng** [comment]
Done
https://github.com/Network-Goods/hypercerts/pull/148
