### ISSUE TITLE
Scope of work for dApp Design

### ISSUE THREAD

**Issue by ccerv1** [Network-Goods/hypercerts#58]
Steps:

- [x] Sketch and prioritize design requirements for dApp: [here](https://network-goods.notion.site/Hypercerts-dApp-Design-Doc-b68a91d1e8634593b2eab33b259b734b)

- [x]  Draft scope of work / job requirements

- [x]  Advertise (including RG network)

**Comment by ccerv1** [comment]
@holkeb @ryscheng tagging you for review. See Notion link above.

**Comment by ryscheng** [comment]
For now, think of this as a playground / sandbox for us to explore different designs:
A designer should be able to goto (once edit access is shared)
https://studio.plasmic.app/projects/38ak4QaubqTqAiZYMMbzfn

and update the design of the live application deployed here:
https://hypercerts.vercel.app/

Let's discuss tomorrow how to best collaborate on design + logic
