### ISSUE TITLE
Assemble existing design assets from hypercerts.xyz landing page and pilot dApp

### ISSUE THREAD

**Issue by ccerv1** [Network-Goods/hypercerts#59]

**Comment by holkeb** [comment]
Here are the old design resources:

- milestone 2 drafts: https://www.figma.com/file/HxdY1EowSYHL2vXOxIGkKv/Hypercerts-Milestone-2-(Draft!)?node-id=0%3A1&t=v6skYXgGWz2pRMwH-0
- Obsidian drafts: https://docs.google.com/document/d/1PvImHmWe8v_F4SWwIdkKpb5xYDThScH_/edit?usp=sharing&ouid=117053116921405948044&rtpof=true&sd=true
- Octavian's design assets - v2: https://www.figma.com/file/F3APlvQ1ezHnPvLrU5cJUS/Hypercerts?node-id=90%3A1306&t=rL99P7O1UwIprma2-0
- Octavian's design assets - v1: https://www.figma.com/file/hawozAKEKc6nVeAhwPWhCH/Impact-Cert-NFT?node-id=0%3A1&t=cqPVQe8OfGnJ1PL8-0

**Comment by ccerv1** [comment]
FYI, all design assets have been merged into [this Figma](https://www.figma.com/file/Dv9Y2cNzFqxa2SUaT8JJmA/Hypercerts-Alpha?node-id=46%3A58&t=zQLgTScUjsMVnTgg-1)
