### ISSUE TITLE
GitHub issue templates

### ISSUE THREAD

**Issue by ryscheng** [Network-Goods/hypercerts#62]
We don't have many outside issues yet, but when we do, we may want to use GitHub issue templates

**Comment by jmoggr** [comment]
FYI: We have github YAML issue forms enabled for our org, if you like to use those.

**Comment by ryscheng** [comment]
Awesome! Forgive my ignorance, where do I find those?

**Comment by jmoggr** [comment]
Put a YAML file in the `.github/ISSUE_TEMPLATE` directory. They allow for more structured issue data. They work alongside the old .md issue templates

Docs:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

**Comment by ryscheng** [comment]
oh ya Im familiar with the process. Sorry I misunderstood that we had standardized issue templates that already exist for some Network-Goods repo. Thanks!

**Comment by ccerv1** [comment]
When this is ready, let's add to our discussions welcome page [here](https://github.com/Network-Goods/hypercerts/discussions/97#discussion-4726303)

**Comment by ryscheng** [comment]
https://github.com/Network-Goods/hypercerts/pull/199

**Comment by ryscheng** [comment]
Linked from the welcome page on discussions
