### ISSUE TITLE
Dynamic SVGs

### ISSUE THREAD

**Issue by ryscheng** [Network-Goods/hypercerts#66]
We want the following:
1.  The hypercert should reflect the claim data (see designs #45) - data stored on IPFS
2.  The hypercert should reflect the current percentage of ownership - data stored on Ethereum
3.  The user may want to upload custom artwork as well (#22)

Currently we do dynamic SVGs on-chain to support 2. But how do we support 1 and 3 then?
Thoughts? @bitbeckers

**Comment by bitbeckers** [comment]
For 1. generation should be on-chain, else it's easy to fake.
That entails that 3. implies users storing their designs on chain, maybe we can make those designs indexed (e.g. store design => get ID 2 => store claim URI with designID 2)

Want to underline that depending on the designs (for instance lots of points which are expressed as strings) can be costly. So in the case of 3, we could offer some guidelines?

**Comment by ccerv1** [comment]
@ryscheng Can we close this out, given the decision in #69 ?

**Comment by ryscheng** [comment]
I was thinking the scope of this would encompass the implementation work as well, I'll assign to @Jipperism since I know he's working on this presently.

**Comment by Jipperism** [comment]
@ccerv1 @ryscheng do we want to provide cropping functionality, when uploading an image for the hypercert?

**Comment by ryscheng** [comment]
I assume you mean editing the image in the app? If it's trivial to add then go ahead, but if it'll take a while to add, it's probably not that important right now as long as we give some guidelines on sizing/aspectRatio to the user?

**Comment by ccerv1** [comment]
Here is the latest thinking on how the user's inputs will affect the SVG creation for the V1:

| Property | Impact on artwork | 
| -------- | -------- | 
| `name`     | Name of the hypercert. The name will appear on the artwork in large UTF-8 text, up to 100 characters. | 
| `project_image` | The artwork will feature a custom image, uploaded by the creator and cropped to a 350 x 350 pixel square. |
| `impact_scope` | The first tag listed by the creator will be displayed on the artwork. This property will also map to a color palette for the art. |
| `work_scope` | Up to the first three tags listed by the creator will be displayed on the artwork. The creator's selection will map to one of 10 vector graphics also displayed as part of the artwork's background. | 
| `work_timeframe` | The artwork will display the date range from the start to the end of the work (YYYY-MM-DD). |
| `collection` | The artwork will display a small icon signifying the collection it belongs to. |

**Comment by ccerv1** [comment]
@ryscheng 👀 

There are currently three templates for creating the hypercert artwork for the Gitcoin Round in the [Figma](https://www.figma.com/file/77rRwbymyoe2prglkXZpok/Hypercert-App?node-id=1051%3A1040).

The in-browser SVG generator should support the following assignments based on the **matching round** that a project belongs to:
- Color palette 
    - OSS = Teal
    - ETH Infra = Purple
    - Climate = Green
- Vector background
   - OSS = Octagonals
   - ETH Infra = Rippling contours
   - Climate = Concentric circles
- The coordinate positioning of the vector background
   - Currently all vectors have the same positioning on the card
   - It could add some visual diversity if we shifted coordinates randomly



![Image](https://user-images.githubusercontent.com/42869436/215869672-4e5f5951-e525-4040-b8a1-760aa04dc307.png)

**Comment by ryscheng** [comment]
Okay, so the way it's currently implemented is that it's hidden from the form.
But when you generate the URL, you can pass in a `backgroundColor`, where the acceptable values are purple, teal, or green.

For example:
https://hypercerts.vercel.app/hypercerts/create?name=IPFS&description=IPFS%20was%20a%20pretty%20cool%20thing.&externalLink=https%3A%2F%2Fipfs.tech%2F&logoUrl=https%3A%2F%2Fcdn-images-1.medium.com%2Fmax%2F1200%2F1%2AlGh_L0ldPWz1kFMcKvj4Qw.png&bannerUrl=https%3A%2F%2Fcloudflare-ipfs.com%2Fipfs%2FQmaiaFjTYmrt97Pd5jSbKq3enfE3wcSriJy96d1Fbgyfeb&impactScopes%5B0%5D=all&impactTimeStart=2023-01-03&impactTimeEnd=2023-01-31&workScopes=ipfs%2C%20docs%0Adev&workTimeStart=2023-01-05&workTimeEnd=2023-01-31&rights%5B0%5D=Public%20Display&contributors=abc%0A123&backgroundColor=purple&fractions=10000

In theory it should be easy to add something similar for vector art, but there's a minor bug that's blocking the same ability with `backgroundVectorArt` = `octagonals` or `contours` or `circles`.
Looking into it.

**Comment by ccerv1** [comment]
I've updated the URL generator to include these additional fields. [Here](https://hypercerts.vercel.app/hypercerts/create?description=Rotki%20is%20an%20open%20source%20portfolio%20tracking%2C%20accounting%2C%20analytics%20and%20tax%20reporting%20tool%20that%20protects%20your%20privacy.%0A%0A%0A%0AThe%20mission%20of%20Rotki%20is%20to%20bring%20transparency%20into%20the%20crypto%20and%20financial%20sectors%20through%20the%20use%20of%20open%20source.%20Most%20importantly%20unlike%20virtually%20every%20other%20competing%20service%20which%20consists%20of%20closed%20source%20SaaS%20onto%20which%20you%20are%20forced%20to%20hand%20over%20all%20your%20financial%20data%2C%20with%20Rotki%20your%20data%20is%20stored%20encrypted%20locally%20in%20your%20computer.%20It%20enables%20you%20to%20take%20ownership%20of%20your%20financial%20data.&name=rotki&externalLink=https%3A%2F%2Frotki.com&logoUrl=https%3A%2F%2Fnftstorage.link%2Fipfs%2Fbafkreiglt4vux2nfbqlmcc4lxnmiuqqoniummtm52ak5a5pq25c6jche5q&bannerUrl=https%3A%2F%2Fnftstorage.link%2Fipfs%2Fbafybeidhdawf7wo6qwlgr72vybrgca3mmnhdko56zwlndy5xff367uqnpa&backgroundColor=purple&backgroundVectorArt=contours&workTimeStart=2022-09-22&workTimeEnd=2023-01-11&impactTimeStart=2023-01-11&impactTimeEnd=indefinite&rights%5B0%5D=Public%20Display&rights%5B1%5D=%C2%ACTransfers&workScopes%5B0%5D=rotki&impactScopes%5B0%5D=all&contributors%5B0%5D=0x9531C059098e3d194fF87FebB587aB07B30B1306&allowlistUrl=ipfs%3A%2F%2Fbafybeied77wecju3mh4ixvgrphhzkfyqwelafsqv2mnpxw57nxselsqnky%2Frotki.csv&fractions=100000&) is an example.

**Comment by ryscheng** [comment]
I'm going to close this out as it's pretty outdated.

If there are subsequent things we want to do, like
- More vector art
- More color options
- Showing fraction ownership (not possible until we store more data on-chain)
- collection images

Please file *new* issues for them. CC @ccerv1
