### ISSUE TITLE
Apply to ETHDenver + SchellingPoint

### ISSUE THREAD

**Issue by ryscheng** [Network-Goods/hypercerts#81]

**Comment by ccerv1** [comment]
- ETHDenver: https://events.ethdenver.com/speaker/registration/form [Due Jan 7]
- Schelling Point: https://docs.google.com/forms/d/e/1FAIpQLSc5exK-vV4FrpOIIHZ0Wxq0O4sLbanmyaSLqMX_3r6gkn7faw/viewform [no deadline]

**Comment by ryscheng** [comment]
https://docs.google.com/document/d/1hwRsOtJvdt1Bxu4k9RLOQ8U7gzDzfeNVzBjSmTZyEVg/edit?usp=sharing

**Comment by ryscheng** [comment]
Submitted the ETHDenver talk.
Feel free to close when done submitting to SchellingPoint.

See the doc for updated text

**Comment by ccerv1** [comment]
Great! Will submit Schelling Point soon

**Comment by ccerv1** [comment]
Submitted
