### ISSUE TITLE
Customizable transfer restrictions per Hypercert

### ISSUE THREAD

**Issue by ryscheng** [Network-Goods/hypercerts#83]
For each hypercert, we want to be able to set how transfers are restricted by the minter at mint time
For example:
- All transfers are disabled
- All transfers are enabled
- Only allow transfer where `from` is the original minter
- Only allow transfers if the `to` is from an allowlist.

Potential implementation pathway:
https://docs.openzeppelin.com/contracts/4.x/api/token/erc1155#ERC1155Pausable
https://docs.openzeppelin.com/contracts/4.x/api/token/erc1155#ERC1155-_beforeTokenTransfer-address-address-address-uint256---uint256---bytes-

**Comment by holkeb** [comment]
If a secondary owner isn’t allowed to transfer the hypercert, they also can’t donate/retire/dedicate it, right? Can we ensure that they can always retire it?

**Comment by ryscheng** [comment]
First draft of transfer restrictions here
https://github.com/Network-Goods/hypercerts-protocol/pull/83

**Comment by ryscheng** [comment]
Closing for now until we get more guidance from legal on whatever else they need in the contract.

**Comment by holkeb** [comment]
@bitbeckers responding here to your telegram message. cc @Jipperism 

For the pilot we want all hypercerts to have the transfer restriction FromCreatorOnly. So this should be hard coded into the frontend for the pilot. However, the contract should allow for all three policies.

@ryscheng also wanted to check to what extent these policies are upgradable, e.g. adding other policies later. At least for me that's still an open question.

**Comment by ryscheng** [comment]
We should be able to add more policies in the future, they just show up as new enum elements.

**Comment by bitbeckers** [comment]
> We should be able to add more policies in the future, they just show up as new enum elements.

Let's make sure to test this when we add in the storage gaps and testing out the upgradeability further
