### ISSUE TITLE
[Ops] Establish impact-scope and work-scope ontologies

### ISSUE THREAD

**Issue by ccerv1** [Network-Goods/hypercerts#84]
Strawman. Need to decide if these are MECE.

````
├── Climate Solutions         # impact-scope
│   ├── renewables            # work-scope
│   ├── carbon-markets     
│   ├── agriculture              
├── Ethereum Infrastructure
│   ├── merge-upgrades
│   ├── feature-releases
└── Open Source Software

**Comment by ccerv1** [comment]
@holkeb copying your message from Slack in here:

> I  went through some of the work scopes. Observations:
- For most of them I would just assign their project name as the work scope as it mostly clearly identifies what they worked on. This is just like "IPFS" being a work scope.
- From the Gitcoin descriptions, it is mostly not possible to define it more specifically for us. The teams could specify it further, just like splitting up IPFS into "go-ipfs-implementation" and "invention of IPFS". We could put that into the instructions.

> @ davidad I would like to run this by you:
- StarkDeFi and JediSwap are two project on StarkNet. So, the work scopes can just be "StarkDeFi" and "JediSwap". In addition we could mark them both as "StarkNet".
- Let's suppose the project ReFi DAO works on "ReFi Passport" and on "ReFi Index" and they want to represent the work on both in one hypercert, so we could use these two tags as scope of work for one hypercert. In addition we could use "ReFi DAO" (just for the sake of the example).
- In the first we would want to have the intersection of StarkNet with each more specific project. In the second we want to add both. How would you represent this, such that it is consistent with the theory and intuitive?

***

This feels to an important design decision. Which user story do we want to build for primarily:
1. As a project creator, I will almost always come with a unique `work_scope` for each hypercert in mind and the `description` is for elaborating on the details of my work
2. As a project creator, I will usually come with a unique `work_scope` but I'm also open to adding a few generic tags to my `work_scope` if it's not hard to do
3. As a project creator, I will first look for generic tags from a dropdown to my `work_scope` and if there's nothing that appeals to me I am willing to do a bit of work to add my own special tags

@holkeb thoughts on this?

**Comment by holkeb** [comment]
@ccerv1 
- If I continue work on a specific project the `work_scope` should be the same like working on IPFS or go-IPFS. So multiple hypercerts should have the same `work_scope` in that case – with the difference in `work_timeframe`.
- Ultimately, it is the creator who will need to decide how fine-grained the hypercert should be, e.g. should it be just one hypercert reg. IPFS or should there be two more specific one reg. invention of IPFS and go-ipfs
- For the pilot we should not leave this too open, the best practice will evolve over time

So I suggest:
4. As a project creator, I will usually pick the project name as the `work_scope` (e.g. "IPFS"). In addition I might specify a certain smaller part of the work (e.g. "go-IPFS implementation"), especially for large projects.

**Comment by ccerv1** [comment]
Per our discussions in Slack, I think we can close this out for the sake of the pilot. I'm on board with having the `work_scope` be set to the name of the project 😄

**Comment by holkeb** [comment]
@ccerv1
