### ISSUE TITLE
[Outreach] Create CTA form for Gitcoin projects

### ISSUE THREAD

**Issue by ccerv1** [Network-Goods/hypercerts#85]
Essentially a Google form or Typeform that indicates "yes, I want to create a hypercert" and confirms basic contact info

**Comment by holkeb** [comment]
@ccerv1 do we still need this? If so, I don't understand when projects would fill this out.

I think https://github.com/Network-Goods/hypercerts/issues/86 is sufficient

**Comment by holkeb** [comment]
ah, I understand the form now reading through the CTA.

- Option 1: We contact the projects before they can mint their hypercert. CTA to fill out a typeform with contact information.
- Option 2: We only contact them when they can mint their hypercert. CTA to mint the hypercert.

You are in favor of option 1?

**Comment by holkeb** [comment]
Update: technically both options are feasible

**Comment by ccerv1** [comment]
@holkeb I think Option 1 is better, starting this Monday. I prepared a form here for you to review: https://forms.gle/fojVAmvqtmJWwmJa7

**Comment by holkeb** [comment]
Great, thanks. Some comments:

1. Reg. "Which rounds are you participating in?": We will know that from the project name, so I would not include this question.
2. Reg. "[Optional] Provide a link to your project's page": I would make it optional, but wouldn't write [optional] here. Or if we don't think it is really necessary, then we can leave it out completely.
3. If I don't know what a hypercert is, I have to click on a link and educate myself before being able to fill out the form. I think that will lower who fills it out a lot. This is also the first time many will hear about hypercerts, so we should make sure a good, simple explanation is available directly. So, I think we need to add something that makes clear the value to the project.
4. Reg. "We need some way of getting in touch with you or the project team.": As we sent them the survey, we already have one way. I would write it more in line with the next question of what is the best channel to reach you.
5. It would be easier if we would communicate with all via email, but I think that's not feasible. So, I like that we ask for their preferred way.
6. Reg. "Are you interested in providing product feedback and/or participating in user research to help improve hypercerts?": Not sure what the best behavioral insights are on this, but I would ask for feedback from all users afterwards. But if we ask before, we shouldn't send the feedback form to all. So, suggestion to not include this.

**Comment by ccerv1** [comment]
Updated with your feedback [here](https://forms.gle/WQ7TRRDoKinCPnCy9). Let me know if you think this is good to go (should we decide to proceed with it still)

**Comment by ccerv1** [comment]
Closing out. Shared internally and with Gitcoin. Think it's good enough!
