### ISSUE TITLE
[Ops] Prepopulate hypercerts fields for all eligible projects

### ISSUE THREAD

**Issue by ccerv1** [Network-Goods/hypercerts#91]

**Comment by ccerv1** [comment]
I'm going to run a simulation using GR15 data for a ~10 projects. I will also create some hypothetical allowlists that may be useful for #24

**Comment by ccerv1** [comment]
### Basic requirements

GIVEN a round that is managed on the new Gitcoin Grants Protocol
WHEN it goes live (ie, the round opens for contributions)
THEN I can index the metadata for each grant
AND THEN map the fields in each grant's metadata to the required fields in the hypercert metadata

WHEN I want to create a hypercert for my project
THEN I can simply click a custom URL that pre-populates the form with my metadata
AND THEN all I need to do is click "create" to mint my hypercert

***

### Resources

1. The Round Manager [subgraph](https://thegraph.com/explorer/subgraphs/BQXTJRLZi7NWGq5AXzQQxvYNa5i1HmqALEJwy3gGJHCr?view=Playground). This allows a user to query all the grants data for a given round. Here is a sample GraphQL query:
```
    rounds(where:{
        id: "0xd95a1969c41112cee9a2c931e849bcef36a16f4c"
    }) {
        id
        projects {
        id
        project
        status
        payoutAddress
        metaPtr {
            protocol
            pointer
        }
        }
    }
    }
```

The addresses for each round are as follows:
- [Climate Solutions](https://grant-explorer.gitcoin.co/#/round/1/0x1b165fe4da6bc58ab8370ddc763d367d29f50ef0): `0x1b165fe4da6bc58ab8370ddc763d367d29f50ef0`
- [Open Source Software](https://grant-explorer.gitcoin.co/#/round/1/0xd95a1969c41112cee9a2c931e849bcef36a16f4c): `0xd95a1969c41112cee9a2c931e849bcef36a16f4c`
- [Ethereum Infrastructre](https://grant-explorer.gitcoin.co/#/round/1/0xe575282b376e3c9886779a841a2510f1dd8c2ce4):`0xe575282b376e3c9886779a841a2510f1dd8c2ce4`

2. Grant Metadata CID (contained in the `metaPtr {pointer}` result) - example: [bafkreibdczj5p2a3mlhczvzjuyanbiatcrslx5xjfjhcpkwhz7th3t5ova](https://cloudflare-ipfs.com/ipfs/bafkreibdczj5p2a3mlhczvzjuyanbiatcrslx5xjfjhcpkwhz7th3t5ova/)

3. Mapping of Grant Metadata to Hypercert Metadata (to be added)

**Comment by jmoggr** [comment]
How are we associating projects with URLs? Alternatively: How does the project owner get the custom URL to click on?

**Comment by ccerv1** [comment]
Essentially:

Grant X --> https://pilot.hypercerts.xyz/claim-hypercert?name=Grant%20X&description=This%20is%20an%20example&workTimeStart=2023-01-17&workTimeEnd=2023-01-17&impactTimeStart=2023-01-17&impactTimeEnd=2023-01-17&fractions=10000 

We still need to work out the mechanism for getting the URL to the project owner :)
It may just be brute force 🐂

**Comment by ccerv1** [comment]
@holkeb I've prepared a Notion page with the current `projects` and `work_scope` data. Would love your review and cleaning up of `work_scope` tags. Per Sascha, no tag should be more than 35 characters if we want it to fit cleanly on the artwork.

**Comment by ccerv1** [comment]
Completed [here](https://github.com/Network-Goods/hypercerts/blob/main/utils/project_urls.md). Will just need to run the scripts again once the round closes tonight.
