### ISSUE TITLE
What are optional / required hypercert metadata fields?

### ISSUE THREAD

**Issue by ccerv1** [Network-Goods/hypercerts#96]
Pilot app takes:
- Name [2-50 chars]
- Description [20-500 chars]
- External link

![Image](https://user-images.githubusercontent.com/42869436/210793578-ee53592c-7745-435f-8fb4-2fcae2eb6cad.png)

Zora takes:
- Name [unicode]
- Description [unicode]
- Image

![Image](https://user-images.githubusercontent.com/42869436/210797320-c3362399-b9d7-4c87-af53-63b840a3ef09.png)

****

Discussion points:

- [ ] Any requirements / limits for the name? 
- [ ] Any requirements / limits for the name? Do we want to support markdown?
- [ ] Do we want to keep the external link field?
- [ ] Do we add a collection field?
- [ ] Do we add a image CID?
- [ ] Which fields are required?

**Comment by holkeb** [comment]
My takes at this point:

1. Call me old-fashioned, but I would find it weird at this point to include emojis in hypercert names. But characters in other languages would make sense to me. @ryscheng is there something from the technical perspective that we should take into account on this decision?
2. Markdown for the name isn't needed, but maybe for the description?
3. The external link could be useful to point to additional resources to understand the project further. However, the links could also be included in the description (if links work there)
4. I would create collections outside of the hypercert itself. For instance I would assign hypercerts of our pilot to collections in the frontend to display them as a collection, but that could change easily and other frontends could display it differently. It is also another categorization in addition to the scope of work and scope of impact, which seems a lot.
5. Image CID is generated automatically, isn't it? @ryscheng 
6. Name and description should be required. External link optional.

**Comment by bitbeckers** [comment]
Re metadata and allowlisting: 
- Optional field to add reference to allowlist data? That could make the allowlist a paralel to 'contributors' and provide a single source of truth for the hypercert data/state

**Comment by holkeb** [comment]
Just to mention it here. In the later versions, I want to allow for additional field via templates. For instance, a funder can create a template for additional fields that she wants to have included on AI safety hypercerts. The template also automatically fills in "AI safety" as one of the impact scopes. The project can easily load this template and fill out the standard hypercert fields and the additional fields from the template.

I assume that all of this is possible via the json blob. If not, let me know :)

**Comment by Jipperism** [comment]
@holkeb I don't see that posing any problems in the future.

**Comment by ryscheng** [comment]
> * Call me old-fashioned, but I would find it weird at this point to include emojis in hypercert names. But characters in other languages would make sense to me. @ryscheng is there something from the technical perspective that we should take into account on this decision?
> * Markdown for the name isn't needed, but maybe useful for the description? Would it be displayed as such on OpenSea for example?
> * The external link could be useful to point to additional resources to understand the project further. However, the links could also be included in the description (if lin1s work there)
> * I would create collections outside of the hypercert itself. For instance I would assign hypercerts of our pilot to collections in the frontend to display them as a collection, but that could change easily and other frontends could display it differently. It is also another categorization in addition to the scope of work and scope of impact, which seems a lot.
> * Image CID is generated automatically, isn't it? @ryscheng
> * Name and description should be required. External link optional.

1. I think we'll probably stick to UTF-8, so emojis are fine, tho we may not want to encourage it.
2. Ya, markdown for description, but not name makes sense.
3. +1 to external link as an optional field
4. I think that makes sense, collections just as a way to organize hypercerts after the fact.
5. Yes, I think we'd upload an image and the SDK would take care of it and generate a CID.

**Comment by ccerv1** [comment]
I'm going to close this out. I think we've discussed the salient issues and agreed on everything. 

Two additional (optional) properties are:
- Allowlist URI
- Collection

For visibility, here is the [doc](https://hackmd.io/@ccerv1/hypercerts-metadata) the captures this.
